{% set name = "python-gooseeye" %}
{% set version = "0.4.0" %}
{% set sha256 = "6af3e47f9746ecc623cf14aec3123d47cd128f7a2a58b8964d37f495a596c572" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseEYE/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GooseEYE

about:
  home: https://github.com/tdegeus/GooseEYE
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Evaluate several geometrical statistical measures on images.'
  description: |
    Library to evaluate several geometrical statistical measures on (ensembles of) 'images'
    (i.e. 1-D, 2-D, or 3-D matrices).
  doc_url: https://gooseeye.rtfd.io
  dev_url: https://github.com/tdegeus/GooseEYE

extra:
  recipe-maintainers:
    - tdegeus
